# Generated by Django 5.0 on 2023-12-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
